// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/setting.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "backend/api/v1"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSettingService is a mock of SettingService interface.
type MockSettingService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingServiceMockRecorder
}

// MockSettingServiceMockRecorder is the mock recorder for MockSettingService.
type MockSettingServiceMockRecorder struct {
	mock *MockSettingService
}

// NewMockSettingService creates a new mock instance.
func NewMockSettingService(ctrl *gomock.Controller) *MockSettingService {
	mock := &MockSettingService{ctrl: ctrl}
	mock.recorder = &MockSettingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingService) EXPECT() *MockSettingServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettingService) Get(ctx context.Context) (*v1.AdminSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*v1.AdminSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingServiceMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingService)(nil).Get), ctx)
}

// GetPublicSiteConfig mocks base method.
func (m *MockSettingService) GetPublicSiteConfig(ctx context.Context, clientVersion string) (*v1.PublicSiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicSiteConfig", ctx, clientVersion)
	ret0, _ := ret[0].(*v1.PublicSiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicSiteConfig indicates an expected call of GetPublicSiteConfig.
func (mr *MockSettingServiceMockRecorder) GetPublicSiteConfig(ctx, clientVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicSiteConfig", reflect.TypeOf((*MockSettingService)(nil).GetPublicSiteConfig), ctx, clientVersion)
}

// TestEmail mocks base method.
func (m *MockSettingService) TestEmail(ctx context.Context, req *v1.TestEmailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestEmail", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestEmail indicates an expected call of TestEmail.
func (mr *MockSettingServiceMockRecorder) TestEmail(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestEmail", reflect.TypeOf((*MockSettingService)(nil).TestEmail), ctx, req)
}

// Update mocks base method.
func (m *MockSettingService) Update(ctx context.Context, req *v1.AdminSettingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSettingServiceMockRecorder) Update(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingService)(nil).Update), ctx, req)
}
