// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/model.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockModelRepository is a mock of ModelRepository interface.
type MockModelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModelRepositoryMockRecorder
}

// MockModelRepositoryMockRecorder is the mock recorder for MockModelRepository.
type MockModelRepositoryMockRecorder struct {
	mock *MockModelRepository
}

// NewMockModelRepository creates a new mock instance.
func NewMockModelRepository(ctrl *gomock.Controller) *MockModelRepository {
	mock := &MockModelRepository{ctrl: ctrl}
	mock.recorder = &MockModelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelRepository) EXPECT() *MockModelRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockModelRepository) Create(ctx context.Context, m2 *model.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, m2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockModelRepositoryMockRecorder) Create(ctx, m2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModelRepository)(nil).Create), ctx, m2)
}

// Delete mocks base method.
func (m *MockModelRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockModelRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModelRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockModelRepository) Get(ctx context.Context, id uint) (model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockModelRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockModelRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockModelRepository) List(ctx context.Context, req *v1.ModelSearchRequest) ([]model.Model, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]model.Model)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockModelRepositoryMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockModelRepository)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockModelRepository) Update(ctx context.Context, id uint, m2 *model.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, m2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockModelRepositoryMockRecorder) Update(ctx, id, m2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModelRepository)(nil).Update), ctx, id, m2)
}
