// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/setting.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSettingRepository is a mock of SettingRepository interface.
type MockSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingRepositoryMockRecorder
}

// MockSettingRepositoryMockRecorder is the mock recorder for MockSettingRepository.
type MockSettingRepositoryMockRecorder struct {
	mock *MockSettingRepository
}

// NewMockSettingRepository creates a new mock instance.
func NewMockSettingRepository(ctrl *gomock.Controller) *MockSettingRepository {
	mock := &MockSettingRepository{ctrl: ctrl}
	mock.recorder = &MockSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingRepository) EXPECT() *MockSettingRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettingRepository) Get(ctx context.Context, key string) (model.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(model.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingRepositoryMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingRepository)(nil).Get), ctx, key)
}

// GetAll mocks base method.
func (m *MockSettingRepository) GetAll(ctx context.Context) ([]model.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSettingRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSettingRepository)(nil).GetAll), ctx)
}

// Set mocks base method.
func (m *MockSettingRepository) Set(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSettingRepositoryMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSettingRepository)(nil).Set), ctx, key, value)
}

// SetMany mocks base method.
func (m *MockSettingRepository) SetMany(ctx context.Context, settings map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMany", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMany indicates an expected call of SetMany.
func (mr *MockSettingRepositoryMockRecorder) SetMany(ctx, settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMany", reflect.TypeOf((*MockSettingRepository)(nil).SetMany), ctx, settings)
}

// UpdateRuntimeConfig mocks base method.
func (m *MockSettingRepository) UpdateRuntimeConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRuntimeConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRuntimeConfig indicates an expected call of UpdateRuntimeConfig.
func (mr *MockSettingRepositoryMockRecorder) UpdateRuntimeConfig(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuntimeConfig", reflect.TypeOf((*MockSettingRepository)(nil).UpdateRuntimeConfig), ctx)
}
