// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/job"
	"backend/internal/repository"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/app"
	"backend/pkg/audit"
	"backend/pkg/email"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"backend/pkg/server/http"
	"backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	syncedEnforcer := repository.NewCasbinEnforcer(db)
	cache := repository.NewCache()
	repositoryRepository := repository.NewRepository(db, syncedEnforcer, cache, logger)
	tokenStore := repository.NewTokenStore(repositoryRepository)
	jwtJWT := jwt.NewJwt(viperViper, tokenStore)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	emailService := email.NewService(viperViper)
	transaction := repository.NewTransaction(repositoryRepository)
	auditAudit := audit.NewAudit(viperViper)
	settingRepository := repository.NewSettingRepository(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jwtJWT, emailService, viperViper, transaction, auditAudit, settingRepository)
	userRepository := repository.NewUserRepository(repositoryRepository)
	authService := service.NewAuthService(serviceService, userRepository, settingRepository)
	authHandler := handler.NewAuthHandler(handlerHandler, authService)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	menuRepository := repository.NewMenuRepository(repositoryRepository)
	avatarStorage := repository.NewAvatarStorage(repositoryRepository, viperViper)
	userService := service.NewUserService(serviceService, userRepository, roleRepository, menuRepository, avatarStorage)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	roleService := service.NewRoleService(serviceService, roleRepository)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	menuService := service.NewMenuService(serviceService, menuRepository)
	menuHandler := handler.NewMenuHandler(handlerHandler, menuService)
	apiRepository := repository.NewApiRepository(repositoryRepository)
	apiService := service.NewApiService(serviceService, apiRepository)
	apiHandler := handler.NewApiHandler(handlerHandler, apiService)
	settingService := service.NewSettingService(serviceService, settingRepository)
	settingHandler := handler.NewSettingHandler(handlerHandler, settingService)
	itemRepository := repository.NewItemRepository(repositoryRepository)
	itemService := service.NewItemService(serviceService, itemRepository, userRepository)
	itemHandler := handler.NewItemHandler(handlerHandler, itemService, userRepository)
	projectRepository := repository.NewProjectRepository(repositoryRepository)
	projectService := service.NewProjectService(serviceService, projectRepository)
	projectHandler := handler.NewProjectHandler(handlerHandler, projectService)
	testCaseRepository := repository.NewTestCaseRepository(repositoryRepository)
	testCaseService := service.NewTestCaseService(serviceService, testCaseRepository)
	testCaseHandler := handler.NewTestCaseHandler(handlerHandler, testCaseService)
	testSuiteRepository := repository.NewTestSuiteRepository(repositoryRepository)
	testSuiteService := service.NewTestSuiteService(serviceService, testSuiteRepository)
	testSuiteHandler := handler.NewTestSuiteHandler(handlerHandler, testSuiteService)
	testPlanRepository := repository.NewTestPlanRepository(repositoryRepository)
	testPlanService := service.NewTestPlanService(serviceService, testPlanRepository)
	testPlanHandler := handler.NewTestPlanHandler(handlerHandler, testPlanService)
	testRecordRepository := repository.NewTestRecordRepository(repositoryRepository)
	testRecordService := service.NewTestRecordService(serviceService, testRecordRepository)
	testRecordHandler := handler.NewTestRecordHandler(handlerHandler, testRecordService)
	deviceRepository := repository.NewDeviceRepository(repositoryRepository)
	deviceService := service.NewDeviceService(serviceService, deviceRepository)
	deviceHandler := handler.NewDeviceHandler(handlerHandler, deviceService)
	userFeedbackRepository := repository.NewUserFeedbackRepository(repositoryRepository)
	userFeedbackService := service.NewUserFeedbackService(serviceService, userFeedbackRepository)
	userFeedbackHandler := handler.NewUserFeedbackHandler(handlerHandler, userFeedbackService)
	bugRepository := repository.NewBugRepository(repositoryRepository)
	bugService := service.NewBugService(serviceService, bugRepository)
	bugHandler := handler.NewBugHandler(handlerHandler, bugService)
	requirementRepository := repository.NewRequirementRepository(repositoryRepository)
	requirementService := service.NewRequirementService(serviceService, requirementRepository)
	requirementHandler := handler.NewRequirementHandler(handlerHandler, requirementService)
	aiProviderRepository := repository.NewAIProviderRepository(repositoryRepository)
	aiProviderService := service.NewAIProviderService(serviceService, aiProviderRepository)
	aiProviderHandler := handler.NewAIProviderHandler(handlerHandler, aiProviderService)
	aiAnalysisResultRepository := repository.NewAIAnalysisResultRepository(repositoryRepository)
	aiAnalysisResultService := service.NewAIAnalysisResultService(serviceService, aiAnalysisResultRepository)
	aiAnalysisResultHandler := handler.NewAIAnalysisResultHandler(handlerHandler, aiAnalysisResultService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, authHandler, userHandler, roleHandler, menuHandler, apiHandler, settingHandler, itemHandler, projectHandler, testCaseHandler, testSuiteHandler, testPlanHandler, testRecordHandler, deviceHandler, userFeedbackHandler, bugHandler, requirementHandler, aiProviderHandler, aiAnalysisResultHandler)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewCache, repository.NewRepository, repository.NewTransaction, repository.NewTokenStore, repository.NewCasbinEnforcer, repository.NewUserRepository, repository.NewAvatarStorage, repository.NewRoleRepository, repository.NewMenuRepository, repository.NewApiRepository, repository.NewSettingRepository, repository.NewItemRepository, repository.NewProjectRepository, repository.NewProjectUserRepository, repository.NewTestCaseRepository, repository.NewTestSuiteRepository, repository.NewTestPlanRepository, repository.NewTestRecordRepository, repository.NewTestCaseExecutionRepository, repository.NewTestSuiteExecutionRepository, repository.NewDeviceRepository, repository.NewUserFeedbackRepository, repository.NewBugRepository, repository.NewRequirementRepository, repository.NewAIProviderRepository, repository.NewAIAnalysisResultRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewAuthService, service.NewUserService, service.NewRoleService, service.NewMenuService, service.NewApiService, service.NewSettingService, service.NewItemService, service.NewProjectService, service.NewTestCaseService, service.NewTestSuiteService, service.NewTestPlanService, service.NewTestRecordService, service.NewDeviceService, service.NewUserFeedbackService, service.NewBugService, service.NewRequirementService, service.NewAIProviderService, service.NewAIAnalysisResultService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewAuthHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewMenuHandler, handler.NewApiHandler, handler.NewSettingHandler, handler.NewItemHandler, handler.NewProjectHandler, handler.NewTestCaseHandler, handler.NewTestSuiteHandler, handler.NewTestPlanHandler, handler.NewTestRecordHandler, handler.NewDeviceHandler, handler.NewUserFeedbackHandler, handler.NewBugHandler, handler.NewRequirementHandler, handler.NewAIProviderHandler, handler.NewAIAnalysisResultHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
